### ISSUE TITLE
I don't fully understand the spatial decorrelation thing, could you enlighten me? 

### ISSUE THREAD

**Issue by Vermeille** [tensorflow/lucid#106]
Hi!

I know this is not exactly your job or even what issues are about, but I'm super interested by your work, and I tried to understand the inner workings of the library. So I stumbled on the spatial decorrelation thing that seems to be central to beautiful visualizations, and couldn't understand that line particularly:
https://github.com/tensorflow/lucid/blob/master/lucid/optvis/param/spatial.py#L48

I'm sorry, I am not exactly well formed about Fourier transform or signal processing, I'm mostly self-taught, but I would be super grateful if you could explain what this formula is, where it does come from, either here or by comments in the code, or even just send me a link to an appropriate article.

I hope I will manage to understand what are both the intuition and the formal understanding behind this file.

Thank you very much, and sorry for the noobish question.

Have a great day!

**Comment by Vermeille** [comment]
Please?

**Comment by ludwigschubert** [comment]
Hey @Vermeille that's not even a "noobish" question, it's just hard to answer. We've added clarifying comments to the code since you asked the question. In Feature Visualization we also gave our intuition: we wanted a parameterization that spatially decorrelated the input space. I don't think there was any additional motivation behind it. If you're worried about understanding this parameterization to understand neural net interpretability, I'd propose to simply move on; our methods work almost as well on "normal" pixel parameterizations. Sorry I couldn't be more helpful!

--- 

Please use the [Stack Overflow tags `tensorflow` & `lucid`](https://stackoverflow.com/questions/tagged/tensorflow+lucid) to ask for help. Stack Overflow provides a better collaborative forum: lots of related questions have been asked there, and some answers may be relevant to you.

When asking for help with a suspected bug, please include a link to demonstrate the issue, preferably as a [Colab notebook](https://colab.research.google.com). It is often impossible to debug from code snippets alone, let alone from error messages or stack traces. Isolate the issue and reduce your code as much as possible before asking for help. Please try to reproduce the bug on one of the models included in `lucid.modelzoo`. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response. 

If you have a question about Lucid’s behavior and want to discuss it with other users, also consider the  `#proj-lucid` channel on the [Distill Community Slack Workspace](https://distillpub.slack.com) which you may [join here](https://join.slack.com/t/distillpub/shared_invite/enQtMzg1NzU3MzEzMTg3LWJkNmQ4Y2JlNjJkNDlhYTU2ZmQxMGFkM2NiMTI2NGVjNzJkOTdjNTFiOGZmNDBjNTEzZGUwM2U0Mzg4NDAyN2E).

Lucid is alpha-status research code, and we appreciate your understanding that this can sometimes mean we will not have the resources to resolve your specific issue—even if it may be an entirely reasonable request in a more mature codebase. Thank you! 🤗

**Comment by Vermeille** [comment]
Hi!

Thank you for your answer. If I understood it correctly that line

`scale = 1.0 / np.maximum(freqs, 1.0 / max(w, h)) ** decay_power`

is here to represent the fact that the energy of frequencies in natural images follows a power low (and then acts as a prior facilitating learning). Is that correct? Then that would mean I could tweak this `decay_rate` to change the shape of that power law, correct?

Thank you for your time, and sorry again.
