### ISSUE TITLE
Visualisation of MNIST dataset gives colored visualisations

### ISSUE THREAD

**Issue by soumilchugh** [tensorflow/lucid#146]
Hi,

I was following this notebook that visualizes MNIST dataset using lucid.  (https://colab.research.google.com/drive/1fm5dXC5C4C85q4hCyq9ite2mERujWezM)
Since MNIST dataset is of grayscale images, why are the resulting visualizations colored? Shouldn't the visualizations be also grayscale?

**Comment by BadrYoubiIdrissi** [comment]
Hello ! 

I think the visualizations aren't necessarily grayscale. That's because the CNN was still trained with 3 channels (Red, green and blue). The weights for each filter don't have to be equal on the three channels. They're even most probably not equal since they are initialized randomly. They even have more reason not to be equal since each channel is independent and the CNN learns a different "filter" on each of the channels. I would think of the weights on each channel as being more parameters for the CNN. It would use these additional parameters to further decrease the training error. 

Since the weights aren't equal on each channel, the feature visualization with optimization would lead to different images.

**Comment by soumilchugh** [comment]
Thanks for the answer. This makes sense. Also, I think lucid just accepts 3 channel images as input and not grayscale so there is on way of obtaining visualizations in grayscale. Is that correct?

**Comment by BadrYoubiIdrissi** [comment]
I have quickly looked into the code and it indeed seems like the input images have 3 channels (as seen in  optvis.param.images). I'm not a maintainer and can't answer you with certainty though. 

It seems there is a naive (a.k.a pixel_image) function in param.spatial but after tinkering a little bit with the MNIST notebook it doesn't seem as easy as modifying the CNN's architecture and the param_f to param.naive((1,28,28,1))... 

Maybe the problem is in generating the visualizations. I don't think the optimization itself supposes a fixed number of channels.

**Comment by ludwigschubert** [comment]
@BadrYoubiIdrissi your assessment reads correct to me; thanks for jumping in! :-) I'd love to accept a PR that lets you specify number of channels on the various parameterizations in `lucid.optvis.param.spatial` and the convenience wrapper in `lucid.optvis.param.images` :-)

Unfortunately there may be additional places all over the codebase that assume 3 or 4 channels—but having easy to specify parameterizations may be a good first step towards a more channel agnonstic lucid. :-)

**Comment by ltetrel** [comment]
Hi everyone,

I am trying to import a keras pre-trained model on MNIST and visualizing the different layers of the model.
As @BadrYoubiIdrissi suggested, I used a regularizer on the input to use gray values.
Whenever I use `render.make_vis_T` I got an internal error :
```
ValueError: Cannot execute operation using `run()`: No default session is registered. Use `with sess.as_default():` or pass an explicit session to `run(session=sess)`
```
I have `tensorflow 1.13.0-rc2` and `lucid v0.3.8` running with the official tf container.

I also tried running the collab notebook but I get the same error,
https://colab.research.google.com/gist/BadrYoubiIdrissi/b2631fddeabf0d8563c6d51cd2055c56/visualising-mnist-features-with-lucid.ipynb#scrollTo=qtYdxnGrZv5x

Thanks,

**Comment by zhangyu2ustc** [comment]
@BadrYoubiIdrissi  your notebook is not accessible anymore. could you please check it?

**Comment by frederikfaye** [comment]
@zhangyu2ustc I can see the notebook fine now.

I have a 4 input channel model, I'd like to visualize. 
@ludwigschubert You wrote
> Unfortunately there may be additional places all over the codebase that assume 3 or 4 channels

You seem to hint at that some code can run with four channels - would I be able to visualize my model using already existing code? if not, what would I need to modify? I'm fine with having the optimization return a (H,W,4)-dim. array, and not a RGB image.

Thanks!
