### ISSUE TITLE
Attribution/Optimization of Objective from an Input Data Image or Batch and not from Gray Noise

### ISSUE THREAD

**Issue by Uiuran** [tensorflow/lucid#159]
Hi, I cant find this issue among your scripts or issue tracker. 
The fact is that it does make sense to me to optmize hidden Objective from an image, because iam on a research to see if a transfered network can be trained to do semantic segmentation on a previous unknown dataset, but i dont wanna to do that in a traditional way, but i wanna hack the hidden layers as you guys are doing.

Hope i stated it clear. So ... Can lucid provide visualizations with objective optimized from any dataset ?

Thankyou cheers.

**Comment by colah** [comment]
Hello! Yes, Lucid can visualize hidden units in vision models trained on other datasets. However, importing models can be a bit challenging.

**Comment by Uiuran** [comment]
But it can **optmize any given image** from the hidden channel tensor objective choosen ? cant find a way to do that

**Comment by colah** [comment]
It sounds like you're asking whether one can initialize the optimization process from a specific image, instead of random noise? This is possible, but requires you to fiddle with parameterizations. We don't have a supported path for doing it.

Depending on your use case, you might like to at the original [deepdream code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/deepdream/deepdream.ipynb), which does do this!
