### ISSUE TITLE
AssertionError in calling render_vis

### ISSUE THREAD

**Issue by Uiuran** [tensorflow/lucid#229]
Tensorflow 1.14.0
Numpy 1.17.4

the following stack just pop-up:
https://pastebin.com/mL4TUMxz

since your code calls on TF to get input Tensor, eval it and use it as input for show, and you use numpy to see the rank and stack and is nan and so on ... the bug may be somewhere there.

Also, i noticed you dont put kwargs in render_vis, in such a fashion that i cant pass w keyword arg and make the visualization bigger. 

Still wondering why not to use matplotlib with jupyter ... 

ps: i finally decided to switch to Lucid to do deep dream and other Artistic things, because it seems to be much more evolved than the initial deep dream code ...

**Comment by Uiuran** [comment]
will try tf 1.15., however the numpy 1.16 version of the tutorial may crash another libs to downgrade.

**Comment by Uiuran** [comment]
I cant get ride of the assertion error even with 0.3.8.

**Comment by colah** [comment]
It sounds like you are running into numerical stability issues while visualizing your model. This could be caused by many issues -- for example, the objective you are visualizing could be exploding, your model may have unstable gradients, and much more.

Please keep in mind that lucid is research code.

**Comment by Uiuran** [comment]
I will close this issue since seems to be the same mentioned earlier, so we keep the discussion in the other issue.
