### ISSUE TITLE
In the inceptionV1 model, what does the positive channel and negative channel means?

### ISSUE THREAD

**Issue by oneTaken** [tensorflow/lucid#90]
Thanks for your work! It's really helpful to know more about the neural network.
And I run the demo code and read the corresponding blog in distil.  
 link is [here](https://distill.pub/2017/feature-visualization/appendix/googlenet/5b.html#5b-2).

Every part has a **neuron**, the **positive** channel, the **diversity**, and the **negative** channel.
Images are beautiful. However, what does the  bold words mean?

**Comment by colah** [comment]
Hello! We're glad you found our article and code helpful! :)

* The **Neuron Objective** visualization is doing a neuron objective (cause the neuron to fire strongly in one position) instead of channel objective (cause the neuron to fire strongly everywhere).  See the [optimization objectives diagram](https://distill.pub/2017/feature-visualization/#optimization-objectives).

* The **Negative Channel** visualization is an image which, instead of causing the neuron to fire strongly, inhibits it strongly. You can think of it as the *opposite* of what the neuron is looking for.  We discuss it briefly in the [diversity section](https://distill.pub/2017/feature-visualization/#diversity) and provide a [notebook](https://colab.research.google.com/github/tensorflow/lucid/blob/master/notebooks/feature-visualization/negative_neurons.ipynb) demonstrating it.

* The **diversity visualization** uses a special technique to create different examples that cause the same neuron to fire. We discuss it in the  [diversity section](https://distill.pub/2017/feature-visualization/#diversity) and provide a [notebook](https://colab.research.google.com/github/tensorflow/lucid/blob/master/notebooks/feature-visualization/neuron_diversity.ipynb) demonstrating it.
